server:
  servlet:
    session:
      tracking-modes: cookie
      cookie:
        max-age: -1

spring:
  application:
    name: myservice

  config:
    import:
      - classpath:/oauth.yml
      - classpath:/actuator.yml
      - classpath:/auth.yml

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        highlight_sql: true
        jdbc:
          batch_size: 100

logging:
  config: classpath:logback.xml